package com.grash.model.enums;

public enum BasicPermission {
    CREATE_EDIT_PEOPLE_AND_TEAMS,
    CREATE_EDIT_CATEGORIES,
    DELETE_WORK_ORDERS,
    DELETE_PREVENTIVE_MAINTENANCE_TRIGGERS,
    DELETE_ASSETS,
    DELETE_PARTS_AND_MULTI_PARTS,
    DELETE_PURCHASE_ORDERS,
    DELETE_METERS,
    DELETE_VENDORS_AND_CUSTOMERS,
    DELETE_CATEGORIES,
    DELETE_FILES,
    DELETE_PEOPLE_AND_TEAMS,
    ACCESS_SETTINGS,
    DELETE_LOCATIONS,
}
