package com.grash.model.enums;

public enum BusinessType {
    BUILDING_MANAGEMENT,
    CHURCH_MANAGEMENT,
    CITY_MAINTENANCE,
    EQUIPMENT_MANAGEMENT,
    FACILITY_MANAGEMENT,
    FARMING_MAINTENANCE,
    FLEET_MANAGEMENT,
    GENERAL_ASSET_MANAGEMENT,
    GYM_FITNESS_MAINTENANCE,
    HOSPITALITY,
    MANUFACTURING_MANAGEMENT,
    PHYSICAL_ASSET_MANAGEMENT,
    PROPERTY_MANAGEMENT,
    RESTAURANT_MANAGEMENT,
    SCHOOL_MAINTENANCE
}
