package com.grash.model.enums;

public enum PlanFeatures {
    PREVENTIVE_MAINTENANCE,
    CHECKLIST,
    FILE,
    PURCHASE_ORDER,
    METER,
    REQUEST_CONFIGURATION,
    ADDITIONAL_TIME,
    ADDITIONAL_COST,
    ANALYTICS,
    REQUEST_PORTAL,
    SIGNATURE,
    ROLE,
    WORKFLOW,
    API_ACCESS,
    WEBHOOK,
    IMPORT_CSV
}
